### ISSUE TITLE
JupyterHub: A "Thing Explainer" overview

### ISSUE THREAD

**Issue by willingc** [jupyterday-atlanta-2016/proposals#6]
## Me

Carol Willing

---
## Abstract

JupyterHub brings the power of Jupyter notebooks to a group of users. University classes, workshops, and user groups can all benefit from notebooks being hosted on a common server. Configuring a JupyterHub server can be complex with many details. 

This presentation will give the audience an overview of JupyterHub's architecture and how to install and configure JupyterHub. Inspired by Randall Munroe's ("xkcd") [Thing Explainer](https://blog.xkcd.com/2015/05/13/new-book-thing-explainer/), we'll break down JupyterHub's complexity into simple understandable concepts. Whether you are new to JupyterHub or have some experience with it, you will leave this talk empowered to give JupyterHub a try.

---
## Affiliation

Project Jupyter
## About Me

Carol Willing is a Research Software Engineer at Cal Poly SLO working full-time on Project Jupyter. She's a Director of the Python Software Foundation. Bridging her love of education, nature, and creating, she mentors people on electronics and software as a Geek in Residence at Fab Lab San Diego.

**Comment by bollwyvl** [comment]
This sounds really awesome! Sounds like a great fit for an _Owning your Jupyter_-style workshop that focuses on on-boarding users and admins!

**Comment by tonyfast** [comment]
@willingc we've got you in the _Up and Running_ workshop, for folk that are either getting started with notebooks, or taking it to the next level with JupyterHub!

**Comment by willingc** [comment]
@tonyfast Got it. I'll circle back on details with you and @bollwyvl on details when I return from vacation on Tuesday. :smile:
