### ISSUE TITLE
JupyterLab Walkthrough

### ISSUE THREAD

**Issue by blink1073** [jupyterday-atlanta-2016/proposals#9]
## Me

Steven Silvester
## Abstract

The audience should get a tour of the latest features of JupyterLab.  The audience should learn about the intended path of JupyterLab development and how third party extensions will be added. 
There is no knowledge requirement, but experience with the existing Jupyter Notebook would be beneficial.  The preferred duration would be 25 minutes, plus 5 minutes for questions.
## About Me

I am a Software Engineer who served 10 years in the US Air Force prior to joining Continuum Analytics in 2015.  I started working on project Jupyter in 2013 working on the Octave magic functions, and have since written kernels for Octave, Matlab, and Scilab.  I am working full time on JupyterLab, the next generation user interface for the Jupyter Notebook.

**Comment by tonyfast** [comment]
Steven (@blink1073 ),

Thank you so much for your submission.  We are really excited to hear about the next generation of Jupyter.  We think that this talk will be a great way to round out the day.  

Thank you so much for traveling to hang out with us!

I am going to close this issue and add you as a speaker on the main site.
